const fs = require("fs");
const os = require("os");
const path = require("path");
const crypto = require("crypto");
const AdmZip = require("adm-zip");
const { DatabaseSync, backup } = require("node:sqlite");
const { createLibrary, duplicateMatches, SCHEMA_VERSION, inTransaction } = require("./db.cjs");

const EXPORT_VERSION = 1;
const csvFields = ["title","author","isbn","genre","year","pages","rating","description","format","location","edition","publisher","readingStatus","currentPage"];
const aliases = { titulo:"title", título:"title", autor:"author", isbn:"isbn", genero:"genre", gênero:"genre", ano:"year", paginas:"pages", páginas:"pages", avaliacao:"rating", avaliação:"rating", descricao:"description", descrição:"description", formato:"format", localizacao:"location", localização:"location", edicao:"edition", edição:"edition", editora:"publisher", estado:"readingStatus", progresso:"currentPage" };
const normalizeHeader = value => String(value||"").normalize("NFD").replace(/[\u0300-\u036f]/g,"").toLowerCase().replace(/[^a-z0-9]/g,"");

function escapeCsv(value) { const text=String(value??""); return /[";,\r\n]/.test(text) ? `"${text.replace(/"/g,'""')}"` : text; }
function parseCsv(text, separator) {
  const sep=separator||(([...text.slice(0,2048)].filter(c=>c===";").length)>[...text.slice(0,2048)].filter(c=>c===",").length?";":",");
  const rows=[];let row=[],field="",quoted=false;
  for(let i=0;i<text.length;i++){const c=text[i];if(quoted){if(c==='"'&&text[i+1]==='"'){field+='"';i++;}else if(c==='"')quoted=false;else field+=c;}else if(c==='"')quoted=true;else if(c===sep){row.push(field);field="";}else if(c==='\n'){row.push(field.replace(/\r$/,"") );rows.push(row);row=[];field="";}else field+=c;}
  if(field||row.length){row.push(field.replace(/\r$/,""));rows.push(row);} return rows.filter(r=>r.some(v=>v.trim()));
}
function mapObject(raw,mapping={}) { const output={}; const passthrough=["cover","notes","featured","tags","noteItems","loans","readingSessions","readingStartedAt","readingCompletedAt"]; for(const [key,value] of Object.entries(raw)){const normalized=normalizeHeader(key);const mapped=mapping[key]||mapping[normalized]||aliases[normalized]||csvFields.find(f=>normalizeHeader(f)===normalized)||passthrough.find(f=>normalizeHeader(f)===normalized);if(mapped)output[mapped]=value;} return output; }
function cleanBook(raw){return {title:String(raw.title||"").trim(),author:String(raw.author||"").trim(),isbn:String(raw.isbn||"").trim(),genre:String(raw.genre||"Outros").trim(),year:Number(raw.year||0),pages:Number(raw.pages||0),rating:Number(raw.rating||0),description:String(raw.description||""),format:String(raw.format||"Físico"),location:String(raw.location||""),edition:String(raw.edition||""),publisher:String(raw.publisher||""),readingStatus:["want_to_read","reading","completed"].includes(raw.readingStatus)?raw.readingStatus:"want_to_read",currentPage:Number(raw.currentPage||0),cover:String(raw.cover||""),notes:String(raw.notes||""),featured:!!raw.featured,tagNames:Array.isArray(raw.tags)?raw.tags.map(t=>typeof t==="string"?t:t.name).filter(Boolean):[],noteItems:Array.isArray(raw.noteItems)?raw.noteItems:[],loans:Array.isArray(raw.loans)?raw.loans:[],readingSessions:Array.isArray(raw.readingSessions)?raw.readingSessions:[]};}
function validateRows(rows,existing){return rows.map((raw,index)=>{const book=cleanBook(raw);const errors=[];if(!book.title)errors.push("Título ausente");if(!book.author)errors.push("Autor ausente");if(!Number.isInteger(book.pages)||book.pages<0)errors.push("Número de páginas inválido");if(!Number.isInteger(book.currentPage)||book.currentPage<0||(book.pages>0&&book.currentPage>book.pages))errors.push("Progresso inválido");const prior=rows.slice(0,index).map(cleanBook);const duplicates=[...duplicateMatches(book,existing).map(m=>({...m,source:"library"})),...duplicateMatches(book,prior).map(m=>({...m,source:"file"}))];return {index,book,valid:errors.length===0,errors,duplicates};});}

function createDataService(getLibrary, replaceLibrary) {
  async function createBackup(destination) {
    const lib=getLibrary(),temp=fs.mkdtempSync(path.join(os.tmpdir(),"bibip-backup-"));
    try { const dbCopy=path.join(temp,"biblioteca.db");await backup(lib.db,dbCopy);const check=new DatabaseSync(dbCopy,{readOnly:true});const ok=check.prepare("PRAGMA integrity_check").get();check.close();if(Object.values(ok)[0]!=="ok")throw new Error("O banco gerado para o backup não passou na verificação de integridade.");const manifest={format:"bibip-backup",formatVersion:1,schemaVersion:SCHEMA_VERSION,createdAt:new Date().toISOString(),app:"Bi-Bip"};fs.writeFileSync(path.join(temp,"manifest.json"),JSON.stringify(manifest,null,2));const zip=new AdmZip();zip.addLocalFile(dbCopy);const covers=path.join(lib.storageRoot,"covers");if(fs.existsSync(covers))zip.addLocalFolder(covers,"covers");zip.addLocalFile(path.join(temp,"manifest.json"));zip.writeZip(destination);return destination;} finally {fs.rmSync(temp,{recursive:true,force:true});}
  }
  function inspectBackup(file) { const zip=new AdmZip(file),entries=zip.getEntries();for(const entry of entries){const normalized=path.posix.normalize(entry.entryName.replace(/\\/g,"/"));if(normalized.startsWith("../")||path.posix.isAbsolute(normalized))throw new Error("O backup contém um caminho inseguro.");}const manifestEntry=zip.getEntry("manifest.json"),dbEntry=zip.getEntry("biblioteca.db");if(!manifestEntry||!dbEntry)throw new Error("Backup incompleto: manifesto ou banco ausente.");let manifest;try{manifest=JSON.parse(manifestEntry.getData().toString("utf8"));}catch{throw new Error("Manifesto inválido.");}if(manifest.format!=="bibip-backup"||manifest.formatVersion!==1)throw new Error("Formato de backup incompatível.");return {zip,manifest}; }
  function validateBackup(file){const {zip,manifest}=inspectBackup(file),temp=fs.mkdtempSync(path.join(os.tmpdir(),"bibip-check-"));try{zip.extractAllTo(temp,true);const check=new DatabaseSync(path.join(temp,"biblioteca.db"),{readOnly:true});const integrity=Object.values(check.prepare("PRAGMA integrity_check").get())[0];check.close();if(integrity!=="ok")throw new Error("O banco do backup está corrompido.");return manifest;}finally{fs.rmSync(temp,{recursive:true,force:true});}}
  async function restoreBackup(file){const {zip}=inspectBackup(file),temp=fs.mkdtempSync(path.join(os.tmpdir(),"bibip-restore-")),safety=path.join(temp,"current-safety.db");const lib=getLibrary();try{zip.extractAllTo(temp,true);const staged=path.join(temp,"biblioteca.db"),check=new DatabaseSync(staged,{readOnly:true});const integrity=Object.values(check.prepare("PRAGMA integrity_check").get())[0];check.close();if(integrity!=="ok")throw new Error("O banco do backup está corrompido.");await backup(lib.db,safety);await replaceLibrary(async storageRoot=>{const currentDb=path.join(storageRoot,"biblioteca.db"),rollback=path.join(storageRoot,"biblioteca.before-restore.db"),oldCovers=path.join(storageRoot,"covers.before-restore");fs.copyFileSync(safety,rollback);for(const suffix of ["-wal","-shm"])fs.rmSync(currentDb+suffix,{force:true});fs.copyFileSync(staged,currentDb);const currentCovers=path.join(storageRoot,"covers"),incoming=path.join(temp,"covers");fs.rmSync(oldCovers,{recursive:true,force:true});if(fs.existsSync(currentCovers))fs.renameSync(currentCovers,oldCovers);try{if(fs.existsSync(incoming))fs.cpSync(incoming,currentCovers,{recursive:true});else fs.mkdirSync(currentCovers,{recursive:true});const validated=createLibrary(storageRoot);if(!validated.integrityCheck())throw new Error("Falha na validação posterior à restauração.");validated.close();fs.rmSync(oldCovers,{recursive:true,force:true});fs.rmSync(rollback,{force:true});}catch(error){for(const suffix of ["-wal","-shm"])fs.rmSync(currentDb+suffix,{force:true});fs.copyFileSync(rollback,currentDb);fs.rmSync(currentCovers,{recursive:true,force:true});if(fs.existsSync(oldCovers))fs.renameSync(oldCovers,currentCovers);throw error;}});return true;}finally{fs.rmSync(temp,{recursive:true,force:true});}}
  function exportJson(destination){const {db}=getLibrary(),books=getLibrary().booksApi.getAll().map(book=>({...book,tags:db.prepare("SELECT t.name,t.color FROM tags t JOIN book_tags bt ON bt.tag_id=t.id WHERE bt.book_id=?").all(book.id),noteItems:getLibrary().booksApi.getNotes(book.id),loans:getLibrary().booksApi.getLoans(book.id),readingSessions:getLibrary().booksApi.getReadingSessions(book.id)}));fs.writeFileSync(destination,JSON.stringify({format:"bibip-export",version:EXPORT_VERSION,exportedAt:new Date().toISOString(),books},null,2),"utf8");return destination;}
  function exportCsv(destination){const books=getLibrary().booksApi.getAll();const data=[csvFields.join(";"),...books.map(book=>csvFields.map(field=>escapeCsv(book[field])).join(";"))].join("\r\n");fs.writeFileSync(destination,"\ufeff"+data,"utf8");return destination;}
  function previewImport(file,mapping={}){const text=fs.readFileSync(file,"utf8").replace(/^\ufeff/,"");let raw=[],sourceHeaders=[];if(path.extname(file).toLowerCase()===".json"){const parsed=JSON.parse(text);if(parsed.format&&parsed.format!=="bibip-export")throw new Error("Formato JSON não reconhecido.");const source=Array.isArray(parsed)?parsed:parsed.books||[];sourceHeaders=source.length?Object.keys(source[0]):[];raw=source.map(item=>mapObject(item,mapping));}else{const matrix=parseCsv(text);if(!matrix.length)throw new Error("CSV vazio.");sourceHeaders=matrix[0];raw=matrix.slice(1).map(values=>mapObject(Object.fromEntries(sourceHeaders.map((h,i)=>[h,values[i]||""])),mapping));}return {file,sourceHeaders,fields:raw.length?Object.keys(raw[0]):[],rows:validateRows(raw,getLibrary().booksApi.getAll())};}
  function importRows(rows,selectedIndexes){const lib=getLibrary(),selected=new Set(selectedIndexes||rows.map(r=>r.index)),valid=rows.filter(r=>selected.has(r.index)&&r.valid);return inTransaction(lib.db,()=>{let imported=0;for(const item of valid){const b=item.book,tagIds=[];for(const name of b.tagNames){let tag=lib.db.prepare("SELECT id FROM tags WHERE name=? COLLATE NOCASE").get(name);if(!tag){const id=lib.tagsApi.add({name,color:"#8c6a58"});tag={id};}tagIds.push(Number(tag.id));}const id=lib.booksApi.add({...b,tagIds});for(const note of b.noteItems){const content=typeof note==="string"?note:note.content;if(content)lib.booksApi.addNote(id,content);}for(const loan of b.loans||[])lib.db.prepare("INSERT INTO book_loans(book_id,borrower,lent_at,due_at,returned_at) VALUES (?,?,?,?,?)").run(id,loan.borrower,loan.lentAt,loan.dueAt||null,loan.returnedAt||null);for(const s of b.readingSessions||[])lib.db.prepare("INSERT INTO reading_sessions(book_id,started_at,completed_at,current_page,status) VALUES (?,?,?,?,?)").run(id,s.startedAt||null,s.completedAt||null,Number(s.currentPage||0),s.status||"want_to_read");imported++;}return {imported,skipped:rows.length-imported};});}
  return {createBackup,validateBackup,restoreBackup,exportJson,exportCsv,previewImport,importRows};
}
module.exports={createDataService,parseCsv,validateRows,EXPORT_VERSION};
